name: warungku_mobile
description: A mobile application for the Warungku online store.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # For making API calls
  http: ^1.1.0
  
  # For simple state management
  provider: ^6.1.1
  
  # For storing session data like token/user_id
  shared_preferences: ^2.2.2

  # For currency formatting
  intl: ^0.18.1

  image_picker: ^1.0.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
